### ISSUE TITLE
Unused images in htw-chur-2019

### ISSUE THREAD

**Issue by dr0i** [hbz/slides#46]
These images are unused and should be either used in the slides or removed:

> [~/git/slides/htw-chur-2019/img] master
$ for i in $(ls); do  cnt=$(grep -c $i ../index.html); if [ $cnt -eq 0  ]; then echo "$i"; fi ; done
gnd-lookup.png
lobid-data.dot
lobid-organisations.png
lobid-resources-api.png
lobid-resources-einzeltreffer.png
lobid-resources.png
openrefine.png
sanderson-2018-loud-22_highlighted.png
sanderson-2018-loud-32_highlighted.png
zdb-nicht-nwbib.png

**Comment by acka47** [comment]
Resolved with d9f462ed5821ed8852b165370268a5c8486e1c16. Closing.
