### ISSUE TITLE
Publish context with CORS header

### ISSUE THREAD

**Issue by acka47** [hbz/slides#47]
For the last step in the JSON-LD exercise for the Zürich event I would like to put the data with external context into the playground and make n-quads out of it. For this, we need the context to be published with a CORS header. In the [example](file:///home/acka47/git/slides/htw-chur-2019/index.html#/79), I use this URL for the context: `https://labs.lobid.org/htw-chur-2019-context.jsonld`

According to https://github.com/json-ld/json-ld.org/issues/366#issuecomment-101034207, we have to add the following to .htaccess for setting the CORS header, :

```
Header set Access-Control-Allow-Origin *
AddType application/ld+json .jsonld
```

**Comment by acka47** [comment]
The context ist at https://github.com/hbz/slides/blob/master/htw-chur-2019/data/context.jsonld

**Comment by dr0i** [comment]
It's now published as https://lobid.org/labs/htw-chur-2019-context.jsonld. There is a .htaccess as you proposed.
