### ISSUE TITLE
Improve CSS for overview page at slides.lobid.org

### ISSUE THREAD

**Issue by acka47** [hbz/slides#52]
As this is now linked to more prominently from lobid.org (see https://github.com/hbz/lobid/issues/405), the overview page should get a similar appearance to the whole lobid.org site.

**Comment by fsteeg** [comment]
Deployed to http://slides.lobid.org

(Deployment is based on GitHub pages, so we have no staging system here)

**Comment by acka47** [comment]
+1 Closing.
