### ISSUE TITLE
Export slides as PDF with 16:9 ratio

### ISSUE THREAD

**Issue by acka47** [hbz/slides#59]
I had problems to export my slides in 16:9 for the KIM workshop. This issue is for documenting how I have done it.

- Install [decktape](https://github.com/astefanutti/decktape)
  - As there are problems with HummusJS and an up-to-date node version (see https://github.com/astefanutti/decktape/issues/201), I downgraded to node 12.14 (using `$ nvm install 12.14`) and then installed decktape using `$ npm install -g decktape`
- Convert the file to pdf with decktape adding `fragments=true` parameter to local file URL to have one slide for each fragment (see https://github.com/astefanutti/decktape/issues/24#issuecomment-250416605) e.g. `$ decktape -s 1920x1080 reveal file:///home/acka47/git/slides/kim-ws-2020/index.html?fragments=true kim-ws-2020.pdf`

**Comment by dr0i** [comment]
Thx for the `decktape` hint! Thx for the detailed explanations. Just a note - for my lightning talk no problems occured.

**Comment by acka47** [comment]
This method does not work anymore, the slides come out wrong, with the view count etc. at the bootom:

![grafik](https://github.com/hbz/slides/assets/160292/b32b7438-2a1c-4fd9-a3e2-c366ae67ae8e)

Until now I have tried these solutions for exporting slides from pad.gwdg.de:
- [The HedgeDoc CLI](https://github.com/hedgedoc/cli) unfortunately does not support PDF export for slides yet. I have tried to download the slides locally with `$ hedgedoc export --slides` and tried the decktape command with the local files. To no surprise thois does not change anything.
- Then I have tried the solution in https://github.com/hackmdio/codimd/issues/33#issuecomment-267508760 with Crhomium which works a bit better, however there are some things broken with regard to images and graphics in text.
- When I tried the same approach in Friefox it looked better, after adjusting image size for some slides it turned out well, except for the first page being blank. I added a blank first page in the markdown, and printed the PDF again. That's not perfect as well, but it hat to suffice.
-

**Comment by acka47** [comment]
Next try: use pandoc with `$ pandoc https://pad.gwdg.de/p/2023-05-25-skohub@bibliocon23?print-pdf -t latex -o slides.pdf`.This gives back:

> pdflatex not found. Please select a different --pdf-engine or install pdflatex 

This is solved by installing `texlive-latex-recommended`: $ sudo apt install texlive-latex-recommended`.  But then  I get the next error:

```
Error producing PDF.
! LaTeX Error: File `letltxmacro.sty' not found.
```

This is solved by installing more than 200MB of `texlive-latex-extra. Next error:

```
Error producing PDF.
! Package inputenc Error: Unicode character ➡ (U+27A1)
(inputenc)                not set up for use with LaTeX.
```

This is [solved by](https://stackoverflow.com/questions/18178084/pandoc-and-foreign-characters) using the `--pdf-engine=xelatex` option for which you need to install `texlive-xetex`.

Finally, this works `$ pandoc --pdf-engine=xelatex https://pad.gwdg.de/p/2023-05-25-skohub@bibliocon23?print-pdf -t latex -o slides.pdf` but the output is far from what  we want.

I assume that how I approached to solve this problem with pandoc was somehow misguided.

**Comment by dr0i** [comment]
I got this working with at least nvm version 20.2.0. Doing this:
`nvm install v20.2.0; npm install -g decktape`  ( this command takes >2m without any output, so just wait).

**Comment by acka47** [comment]
> I got this working with at least nvm version 20.2.0. Doing this:
`nvm install v20.2.0; npm install -g decktape`

Thanks, @dr0i . Yes, this works with slides from slides.lobid.org but unfortunately not with HedeDoc slides from pad.gwdg.de (althoug it also uses reveal.js)...

**Comment by acka47** [comment]
> Thanks, @dr0i . Yes, this works with slides from slides.lobid.org but unfortunately not with HedeDoc slides from pad.gwdg.de (althoug it also uses reveal.js)...

I am happy with the approach described in https://github.com/hbz/slides/issues/59#issuecomment-1564069106 . The only annoying thing is that I have to add a slide before the first one and remove it later in the PDF as otherwise the title slide is made blank. For removing the first slide from the PDF I used pdftk on the command line, e.g.: `$ pdftk input.pdf cat 2-82 output output.pdf`, where "82" has to be set to the number of te last slide.

**Comment by acka47** [comment]
Once again I ran into problems with creating a PDF from a HedgeDoc-based presentation. It's this one: https://pad.lobid.org/p/skohub@nfdi4ing-conference

This time the headings came out wrong and the logo wasn't taken over.

I've then tried another variant: as decktape created the slides with the footer (see https://github.com/hbz/slides/issues/59#issuecomment-1564069106), I removed the footer in the CSS by adding:

```
    .footer {
        display: none;
    }
```

However, althuugh the text in the footer is not shown, the space is still occupied in the bottom of each slide and there are problems with emojis, e.g.:

![image](https://github.com/hbz/slides/assets/160292/251cf6f9-3268-4142-a118-6cdbe69d7c30)

**Comment by sroertgen** [comment]
After struggling with the pandoc approach for some time I gave decktape a try. And it just worked beautifully:

`decktape https://pad.lobid.org/p/skohub@nfdi4ing-conference slides.pdf`

being on manjaro I just installed decktape from the AUR
