### ISSUE TITLE
Feature Request: RSS-Feed For New Slides

### ISSUE THREAD

**Issue by hejjoe** [hbz/slides#81]
Similar to 

https://blog.lobid.org/feed.xml

it would be very nice to have

https://slides.lobid.org/feed.xml

**Comment by fsteeg** [comment]
Thanks for the suggestion!

The current [slides](https://slides.lobid.org/) page is a manually maintained static HTML page, so we can't really add a feed there. What we could do is to add RSS feeds for the generated publication lists used in our product, project, and member pages (e.g. for [lobid](http://lobid.org/product/lobid)). Based on that, we could add a publication list (with RSS feed) to the [team](http://lobid.org/team) page for all publications (about any product or project, by any member). This could then replace the current slides page.

**Comment by fsteeg** [comment]
The way to implement this in Gatsby was a little different from what I imagined. As a result, we don't have separate feeds for product, project, and member pages for now, but only a main feed for all publications by the team. The 20 most recent publications are now listed on the main team page, with a link to the full RSS feed.

Deployed to stage: http://stage.lobid.org/team

**Comment by acka47** [comment]
+1 It works and I think it is very cool that my feedreader fetches all the contents: the slides from slides.lobid.org as well as the HTML from DeGruyter for https://doi.org/10.1515/abitech-2022-0012.
